version: '3.8'

services:
  postgres:
    container_name: postgres-db
    image: postgres:latest
    environment:
      POSTGRES_DB: agilbackend
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  eureka-server:
    image: your_eureka_image
    build:
      context: ./eureka
    ports:
      - 8761:8761
    networks:
      - spring-demo

  api-gateway:
    image: your_api_gateway_image
    build:
      context: ./api-gateway
    ports:
      - 8080:8080
    networks:
      - spring-demo
    depends_on:
      - eureka-server

  gerant-service:
    image: your_gerant_service_image
    build:
      context: ./gerant
    ports:
      - 8081:8081
    networks:
      - spring-demo
    depends_on:
      - postgres
      - eureka-server

  commande-service:
    image: your_commande_service_image
    build:
      context: ./commande
    ports:
      - 8082:8082
    networks:
      - spring-demo
    depends_on:
      - postgres
      - eureka-server

  reclamation-service:
    image: your_reclamation_service_image
    build:
      context: ./reclamation
    ports:
      - 8083:8083
    networks:
      - spring-demo
    depends_on:
      - postgres
      - eureka-server

  intervenant-service:
    image: your_intervenant_service_image
    build:
      context: ./intervenant
    ports:
      - 8084:8084
    networks:
      - spring-demo
    depends_on:
      - postgres
      - eureka-server

  utilisateur-service:
    image: your_utilisateur_service_image
    build:
      context: ./utilisateur
    ports:
      - 8085:8085
    networks:
      - spring-demo
    depends_on:
      - postgres
      - eureka-server

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres_data:
    driver: local
