server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
       prefer-ip-address: true

  spring:
  application:
    name: api-gateway

spring:
  cloud:
    gateway:
      routes:
        - id: gerant-service
          uri: lb://gerant-service
          predicates:
            - Path=/gerant/**
        - id: commande-service
          uri: lb://commande-service
          predicates:
            - Path=/commande/**
        - id: reclamation-service
          uri: lb://reclamation-service
          predicates:
            - Path=/reclamation/**
        - id: intervenant-service
          uri: lb://intervenant-service
          predicates:
            - Path=/intervenant/**
        - id: utilisateur-service
          uri: lb://utilisateur-service
          predicates:
            - Path=/utilisateur/**
